polycon_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'main#home'
  get '/grids/grid_generator', to: 'grids#grid_generator'
  get '/grids/download', to: 'grids#generate_grid'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel-all', action: 'cancel_all'
        get 'filter-index', action: 'filter_index'
      end
      member do
        get 'reschedule', action: 'reschedule'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

polycon_app/app/models/appointment.rb
class MinutesValidator < ActiveModel::Validator
  def validate(record)
      unless ((record.date.min == 0) or (record.date.min == 30))
          record.errors.add :base, "This appointment's date format is invalid"
      end
  end
end

class HourValidator < ActiveModel::Validator
  def validate(record)
      unless ((record.date.hour >= 8) and (record.date.hour <= 19))
          record.errors.add :base, "This appointment's date format is invalid"
      end
  end
end


class Appointment < ApplicationRecord
  belongs_to :professional
  validates :date, presence: true
  validates_with HourValidator
  validates_with MinutesValidator
  validates :patient_name, presence: true
  validates :patient_surname, presence: true
  validates :patient_phone, presence: true
  validates :professional_id, presence: true
  validates_uniqueness_of :professional_id, scope: :date 
end

polycon_app/app/controllers/appointments_controller.rb
require 'date'
class AppointmentsController < ApplicationController
    load_and_authorize_resource
    def index
        @appointments = Appointment.where(professional: params[:professional_id]).order(:date).paginate(:page => params[:page], :per_page => 10)
        @professional = Professional.find(params[:professional_id])
    end

    def new
        @appointment = Appointment.new
        @professional = Professional.find(params[:professional_id])
    end

    def create
        @appointment = Appointment.new(appointment_params)
        @professional = Professional.find(@appointment.professional_id)
        error_msg = validation(appointment_params)
        if error_msg.empty? and @appointment.save
            redirect_to professional_appointments_path(@professional), :alert => "Turno agendado con éxito"
        else
            redirect_to new_professional_appointment_path(@professional), :alert => "No se pudo agendar el turno. #{error_msg}"
        end
    end

    def show
        @appointment = Appointment.find(params[:id])
        @professional = Professional.find(@appointment.professional_id)
    end

    def edit
        @appointment = Appointment.find(params[:id])
        @professional = Professional.find(params[:professional_id])
    end

    def update
        @appointment = Appointment.find(params[:id])
        @professional = Professional.find(@appointment.professional_id)
        error_msg = validation(appointment_params)
        if error_msg.empty? and @appointment.update(appointment_params)
            redirect_to  professional_appointments_path(@professional), :alert => "Modificación exitosa"
        else
            redirect_to [@professional, @appointment], :alert => "No se pudo modificar los datos del turno. #{error_msg}"
        end
    end

    def reschedule
        @appointment = Appointment.find(params[:id])
        @professional = Professional.find(@appointment.professional_id)
    end

    def destroy
        @appointment = Appointment.find(params[:id])
        @professional = Professional.find(@appointment.professional_id)
        @appointment.delete
        redirect_to professional_appointments_path(@professional), :alert => "Se canceló el turno"
    end

    def cancel_all
        @appointments = Appointment.where(professional: params[:professional_id]).delete_all
        redirect_to professionals_path, :alert => "Se cancelaron todos los turnos"
    end

    def filter_index
        next_day = Date.strptime(params[:date_filter], "%Y-%m-%d") + 1
        @appointments = Appointment.where(date: (params[:date_filter]..next_day.to_s)).where(professional_id: params[:professional_id]).order(:date).paginate(:page => params[:page], :per_page => 10)
        @professional = Professional.find(params[:professional_id])
    end

    private
        def appointment_params
            params.require(:appointment).permit(:date, :patient_name, :patient_surname, :patient_phone, :notes, :professional_id)
        end

        def validation(appointment_params)
            error_msg = ""
            appointment_aux = Appointment.where(professional: appointment_params[:professional_id]).where(date: appointment_params[:date])
            if !appointment_aux.empty?
                error_msg = error_msg + "Ya existe un turno en este horario para este profesional.\n"
            end
            return error_msg
        end
end

polycon_app/app/helpers/appointment_helper.rb
module AppointmentHelper
end

polycon_app/app/views/appointments/edit.html.erb
<div><h2>Editar un Turno</h2></div><br>
<%= form_with(model: [@professional, @appointment]) do |a| %>
    <div class="form-group row">
        <%= a.label :patient_name, "Nombre del paciente:", :class=>"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_name, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :patient_surname, "Apellido del paciente:", :class => "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_surname, required:'true', :class => "form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :patient_phone, "Teléfono del paciente:", :class => "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_phone, required:'true', :class => "form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :notes, "Notas(opcional):", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= a.text_area :notes, :class => "form-control" %>
        </div>
    </div>
    <div>
        <%= a.text_field :professional_id, value: @professional.id, type:'hidden'%>
    </div>
    <div>
        <%= link_to 'Volver', professional_appointments_path(@professional), :class =>'btn btn-mini btn-outline-dark'%>
        <%= a.submit "Guardar", :class =>'btn btn-mini btn-outline-success'%>
    </div>
<% end %>

polycon_app/app/views/appointments/filter_index.html.erb
<div><h2>Listado de Turnos de <%=@professional.name%><h2></div><br>
<table class="table">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Paciente</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <% @appointments.each do |a| %>
        <tr>
            <td><%= l a.date, format: :short %></td>
            <td><%= a.patient_name + " "+ a.patient_surname%></td>
            <td>
                <%= link_to "Ver", [@professional, a], :class => 'btn btn-mini btn-outline-dark'%>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= link_to "Volver", professional_appointments_path(@professional), :class => 'btn btn-mini btn-outline-dark'%>
<% if can? :create, Appointment %>
    <%= link_to "Nuevo Turno", new_professional_appointment_path(@professional), :class => 'btn btn-mini btn-outline-success'%>
<% end %>
<div><br>
<%= will_paginate @appointments , renderer: BootstrapPagination::Rails %>
</div>

polycon_app/app/views/appointments/index.html.erb
<div>
<h2>Listado de Turnos de <%=@professional.name%></h2>
</div><br>
<%=form_with url: filter_index_professional_appointments_path(@professional), method: :get do |form|%>
    <div class="form-group row">
        <%= form.label :date_filter, "Filtrar por fecha:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= form.date_field :date_filter, required:'true', :class=>"form-control" %>
        </div>
    </div>
    <div>
        <%= form.text_field :professional_id, value: @professional.id, type:'hidden'%>
    </div><br>
        <%= form.submit "Filtrar", :class => 'btn btn-mini btn-outline-dark'%>
<% end %>
<br>
<table class="table">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Paciente</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <% @appointments.each do |a| %>
        <tr>
            <td><%= l a.date, format: :short %></td>
            <td><%= a.patient_name + " "+ a.patient_surname %></td>
            <td>
                <%= link_to "Ver", [@professional, a], :class => 'btn btn-mini btn-outline-dark'%>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= link_to "Volver", professionals_path, :class => 'btn btn-mini btn-outline-dark'%>
<% if can? :create, Appointment %>
    <%= link_to "Nuevo Turno", new_professional_appointment_path(@professional), :class => 'btn btn-mini btn-outline-success'%>
<% end %>
<% if can? :cancel_all, Appointment %>
    <%= link_to "Cancelar todos", cancel_all_professional_appointments_path(@professional), method: :delete, data: {confirm: 'Deseas cancelar todos los turnos de este profesional?'}, :class => 'btn btn-mini btn-outline-danger'%>
<% end %>
<div><br>
<%= will_paginate @appointments , renderer: BootstrapPagination::Rails %>
</div>

polycon_app/app/views/appointments/new.html.erb
<div><h2>Agendar un turno</h2><div><br>
<p class="text-secondary">Los turnos deben agendarse en un rango de horario de 8:00 a 19:30 (inclusive) y los minutos deben ser 00 o 30</p><br>
<%= form_with(model: [@professional, @appointment]) do |a| %>
    <div class="form-group row">
        <%= a.label :date, "Fecha y hora:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= a.datetime_field :date, required:'true'%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :patient_name, "Nombre del paciente:", :class=>"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_name, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :patient_surname, "Apellido del paciente:", :class => "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_surname, required:'true', :class => "form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :patient_phone, "Teléfono del paciente:", :class => "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= a.text_field :patient_phone, required:'true', :class => "form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= a.label :notes, "Notas(opcional):", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= a.text_area :notes, :class => "form-control" %>
        </div>
    </div>
    <div>
        <%= a.text_field :professional_id, value: @professional.id, type:'hidden'%>
    </div>
    <div>
        <%= link_to 'Volver', professional_appointments_path(@professional), :class =>'btn btn-mini btn-outline-dark'%>
        <%= a.submit "Crear", :class =>'btn btn-mini btn-outline-success'%>
    </div>
<% end %>

polycon_app/app/views/appointments/reschedule.html.erb
<div><h2>Reagendar un Turno</h2></div><br>
<p class="text-secondary">Los turnos deben agendarse en un rango de horario de 8:00 a 19:30 (inclusive) y los minutos deben ser 00 o 30</p><br>
<%= form_with(model: [@professional, @appointment]) do |a| %>
    <div class="form-group row">
        <%= a.label :date, "Fecha: " , :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= a.datetime_field :date, required:'true', :class=>"form-control"  %>
        </div>
    </div>
    <div>
        <%= a.text_field :professional_id, value: @professional.id, type:'hidden'%>
    </div><br>
    <div>
        <%= link_to 'Volver', professional_appointments_path(@professional), :class => 'btn btn-mini btn-outline-dark' %>
        <%= a.submit "Guardar", :class => 'btn btn-mini btn-outline-success'%>
    </div>
<% end %>

polycon_app/app/views/appointments/show.html.erb
<div>
<h2>Detalles</h2>
</div><br>
<table class="table">
    <thead>
        <tr>
            <th>Profesional</th>
            <th>Fecha</th>
            <th>Nombre del paciente</th>
            <th>Apellido del paciente</th>
            <th>Telefono del paciente</th>
            <th>Notas</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td><%= @professional.name %></td>
        <td><%= l @appointment.date, format: :short %></td>
        <td><%= @appointment.patient_name %></td>
        <td><%= @appointment.patient_surname %></td>
        <td><%= @appointment.patient_phone %></td>
        <td><%= @appointment.notes %></td>
        <td>
            <% if can? :edit, Appointment %>
                <%= link_to "Editar", edit_professional_appointment_path(@professional, @appointment), :class => 'btn btn-mini btn-outline-dark'%>
            <% end %>
            <% if can? :update, Appointment %>
                <%= link_to "Reagendar", reschedule_professional_appointment_path(@professional, @appointment), :class => 'btn btn-mini btn-outline-dark'%>
            <% end %>
            <% if can? :destroy, Appointment %>
                <%= link_to "Cancelar", [@professional, @appointment], method: :delete, data: { confirm: "Desea cancelar este turno?"}, :class => 'btn btn-mini btn-outline-danger' %>
            <% end %>
        </td>
    </tr>
    </tbody>
</table>
<%= link_to 'Volver', professional_appointments_path(@professional), :class => 'btn btn-mini btn-outline-dark'%>