polycon_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'main#home'
  get '/grids/grid_generator', to: 'grids#grid_generator'
  get '/grids/download', to: 'grids#generate_grid'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel-all', action: 'cancel_all'
        get 'filter-index', action: 'filter_index'
      end
      member do
        get 'reschedule', action: 'reschedule'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

polycon_app/app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments

    validates :name, presence: true, uniqueness: true
    validates :phone, presence: true
    validates :email, presence: true
    validates :specialty, presence: true
end

polycon_app/app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController 
    load_and_authorize_resource
    def index
        @professionals = Professional.all.order(:name).paginate(:page => params[:page], :per_page => 10)
    end
    
    def new
        @professional = Professional.new
    end

    def create
        @professional = Professional.new(professional_params)
        error_msg = validation(professional_params)
        if error_msg.empty? and @professional.save
            redirect_to professionals_path, :alert => "Profesional creado con éxito"
        else
            redirect_to new_professional_path, :alert => error_msg
        end
    end

    def edit
        @professional = Professional.find(params[:id])
    end

    def update
        @professional = Professional.find(params[:id])
        error_msg = validation(professional_params)
        if error_msg.empty? and @professional.update(professional_params)
            redirect_to professionals_path, :alert => "Modificación exitosa"
        else
            redirect_to edit_professional_path(@professional), :alert => error_msg
        end
    end

    def show
        @professional = Professional.find(params[:id])
    end

    def destroy
        query = Appointment.where(professional: params[:id])
        if (query.empty?)
            @professional = Professional.find(params[:id])
            @professional.delete
            redirect_to professionals_path, :alert => "Se eliminó el profesional"
        else
            redirect_to professionals_path, :alert => "No se pudo eliminar el profesional ya que posee turnos agendados"
        end
    end

    private
        def professional_params
            params.require(:professional).permit(:name, :phone, :email, :specialty)
        end

        def validation(professional_params)
            error_msg = ""
            professional_aux = Professional.where(name: professional_params[:name])
            if !professional_aux.empty?
                error_msg = error_msg + "Ya existe un profesional con este nombre.\n"
            end
            return error_msg
        end
end

polycon_app/app/helpers/professional_helper.rb
module ProfessionalHelper
end

polycon_app/app/views/professionals/edit.html.erb
<div><h2>Editar un Profesional</h2></div><br>
<%= form_for @professional do |p| %>
    <div class="form-group row">
        <%= p.label :name, "Nombre del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :name, required:'true', :class => "form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :phone, "Teléfono del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :phone, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :email, "Email del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.email_field :email, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :specialty, "Especialidad del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :specialty, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div><br>
        <%= link_to "Volver", professionals_path, :class =>'btn btn-mini btn-outline-dark'%>
        <%= p.submit "Guardar", :class =>'btn btn-mini btn-outline-success' %>
    </div>
<% end %>

polycon_app/app/views/professionals/index.html.erb
<h2>Listado de Profesionales</h2><br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Teléfono</th>
            <th scope="col">Email</th>
            <th scope="col">Especialidad</th>
            <th scope="col">Acciones</th>
        <tr>
    </thead>
    <tbody>
    <% @professionals.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.phone %></td>
            <td><%= p.email %></td>
            <td><%= p.specialty %></td>
            <td>
                <% if can? :edit, Professional %>
                    <%= link_to "Editar", edit_professional_path(p), :class => 'btn btn-mini btn-outline-dark'%>
                <% end %>
                <% if can? :read, Professional %>
                    <%= link_to "Turnos", professional_appointments_path(p), :class => 'btn btn-mini btn-outline-dark'%>
                <% end %>
                <% if can? :destroy, Professional %>
                    <%= link_to "Eliminar", p, method: :delete, data: { confirm: "Desea eliminar este profesional?"}, :class => 'btn btn-mini btn-outline-danger' %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>
<% if can? :create, Professional %>
    <%= link_to "Nuevo Profesional", new_professional_path, :class => 'btn btn-mini btn-outline-success'%>
<% end %>
<div><br>
<%= will_paginate @professionals , renderer: BootstrapPagination::Rails %>
</div>

polycon_app/app/views/professionals/new.html.erb
<div><h2>Nuevo Profesional</h2></div><br>
<%= form_for @professional do |p| %>
    <div class="form-group row">
        <%= p.label :name, "Nombre del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :name, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :phone, "Teléfono del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :phone, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :email, "Email del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.email_field :email, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group row">
        <%= p.label :specialty, "Especialidad del profesional:", :class => "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
            <%= p.text_field :specialty, required:'true', :class=>"form-control"%>
        </div>
    </div>
    <div>
        <%= link_to "Volver", professionals_path, :class =>'btn btn-mini btn-outline-dark'%>
        <%= p.submit "Crear", :class =>'btn btn-mini btn-outline-success'%>
    </div>
<% end %>

polycon_app/app/views/professionals/show.html.erb
<table>
    <tr>
        <thead>
            <th>Nombre</th>
        </thead>
    </tr>
    <tr>
        <td><%= @professional.name %></td>
    </tr>
</table>
<%= link_to "Volver", professionals_path%>